### ISSUE TITLE
Please see #10 - SendPage not working? Diagnostic steps? 

### ISSUE THREAD

**Issue by ron-watt** [stadler/SendPage#11]
Renewed issues.  Some diagnostics steps attempted, with v. 2.1  See closed issue #10 for more.

**Comment by stadler** [comment]
Hi ron-watt
Thanks again for letting me know.
There was indeed a problem in version 2.1. It was fixed in the meantime in version 2.1.1.
I hope that now everything works again as expected.
Regards, stadler
