### ISSUE TITLE
Sendpage v2.1 totally dead - not working

### ISSUE THREAD

**Issue by geetee24** [stadler/SendPage#12]
Latest Sendpage v2.1 update is totally broken.  mailto link works - brings up windows 7 Thunderbird yet SendPage does nothing.  Nada. totally broken.,  how can I revert to the old version that worked for years :(

windows 7 64 bit.
thunderbird client responds to mailto:......

Thanks

**Comment by stadler** [comment]
Hi
Yes there was a problem in version 2.1 which has been fixed with version 2.1.1 in the mean time.
Let me know if you still have any problems.
Regards, stadler
