### ISSUE TITLE
send this page not workig 

### ISSUE THREAD

**Issue by marrti** [stadler/SendPage#13]
Hello i have chrome latest version and send this page is not working . when i click right mouse button and then click 'send this page' nothing happens.

i hope you can fix that is a super addon !! 

best regards, marrti

**Comment by stadler** [comment]
Hi
Thanks for reporting the issue. It should be fixed in the mean time.
Make sure you have version 2.1.1 of the extension.
Let me know if you still have problems with this version.
Regards, stadler
