### ISSUE TITLE
Doesn't quite work with Youtube

### ISSUE THREAD

**Issue by RichMorin** [stadler/SendPage#15]
I tried SendPage today with a YouTube link: https://www.youtube.com/watch?v=Y5seI0eJZCg.
It opened my Mail Client and put the page title into the subject but instead of the URL, it inserted "undefined".

I have to say that this was better than two other "Send Email" Chrome extensions I tried. Neither of them even opened my mail client (Mail.app).

Chrome  50.0.2661.102 (64-bit)
Mac OS X 10.9.5

**Comment by RichMorin** [comment]
It's not just YouTube. Every page I try to send comes up with the URL "undefined".

**Comment by stadler** [comment]
Hi
Does this happen when you use SendPage through the context menu (right clicking on the page) or by using the icon at the right of the url bar?

Cause I experience this issue when using the icon besides the url bar.
I will have a look at this...

**Comment by stadler** [comment]
Should work again in version 2.3. Have fun!
