### ISSUE TITLE
Not working after latest Windows 10 update

### ISSUE THREAD

**Issue by gymshu** [stadler/SendPage#16]
Will not work after latest windows 10 update

**Comment by stadler** [comment]
Hi
What do you mean by 'will not work'?
And do [mailto links](mailto:test@example.com) in general work?
And did it work before windows 10? With windows 7?

**Comment by gymshu** [comment]
It was working fine with Windows 10 before yesterday.  It would open up an e-mail in Outlook with the link.  After the update, nothing happens - nothing.

 

Jim_Blue_Brush

**Comment by stadler** [comment]
But mailto Links like e.g. [mailto:test@example.com](mailto:test@example.com) work?

**Comment by gymshu** [comment]
I click on this and absolutely nothing happens.

 



 

Jim_Blue_Brush

**Comment by stadler** [comment]
Ok, then you need to make sure that you have a program that is registered as default mail client and that can handle those mailto links. This has nothing to do with SendPage.
See: http://www.slipstick.com/outlook/outlook-not-recognized-default-email-client/

**Comment by gymshu** [comment]
The update reset my defaults - it's working fine now.   Thanks for the hints.

 

Jim_Blue_Brush
