### ISSUE TITLE
send page extension does not work

### ISSUE THREAD

**Issue by zayuma** [stadler/SendPage#17]
hi,
yesterday these extension works propely ... now, this day no issue with these extension ! why ? j d'ont understand ... after uninstall and re install the issue is same ... what can i do ? whant can i change ... i use these extension along the time, all the days for publishing text and other on my web site ... thank you.
my config : linux ubuntu 64 16.04 lts my navigator : chrome for linux ubuntu 64 my local mailing : thunderbird 45.8.0 for linux ubuntu 64. help me please !!!
ray

**Comment by zayuma** [comment]
depuis ce matin extension hs ne fonctionne plus du tout sous linux ubuntu 64 avec chromium et thunderbird de mozilla !
c' est vraiment le merdier, surtout quand on utilise ce genre de module tout au long de la journée ... pas de pub ou si pub bien mauvaise ... un administrateur de site web !

**Comment by stadler** [comment]
Hi
Did you have a look at the Troubleshoot section:
https://github.com/stadler/SendPage#troubleshoot

Probably your Mail Client is not registered as default mail client and therefore doesn't listen to mailto: Links.
Let me know if this doesn't help.
