### ISSUE TITLE
Does not appear to work in Vivaldi 64-bit

### ISSUE THREAD

**Issue by Dan-Essin** [stadler/SendPage#18]
1 - Choose Send Mail from context menu
2 - New tab appears momentarily, then disappears
3 - Mail client (tbird) does not open

**Comment by stadler** [comment]
Do Mailto Links in general work? 
E.g. does the Mail-Client open when you click this: [mailto:test@example.com](mailto:test@example.com)
If not please make sure to have your Client registered as mailto protocol handler.
