### ISSUE TITLE
Opens gmail, unable to autofill email address

### ISSUE THREAD

**Issue by ClarkRobbins** [stadler/SendPage#20]
When I use to right click a webpage and left click send page, it would open gmail, as it still does now. However once I started to type in an email address it would autofill/guess the one I wanted and move on. 

It no longer autofills/guesses the email address I started and have to type the entire email address out.

This is only on the PC with google chrome and accessing gmail through the browser extension. If I open gmail it will work as expected. Any ideas why this function was broken? It worked up till about a week or so ago. I uninstalled and reinstalled the extension with no resolution to the problem.

**Comment by stadler** [comment]
Hi
Yes I agree that there seems that something is odd here.
However this seems to be a Problem of GMail and their handling of mailto links. Because this also happens when clicking on any mailto link.
Sorry I can't help here.

**Comment by ClarkRobbins** [comment]
That's odd, mailto: links work for me on Google Chrome latest version.

Respectfully,

Clark D Robbins, Code Official
Taylor Borough
122 Union Street
Taylor, PA 18517-1772
(570) 562-1400 Ext. 111

http://www.taylorborough.com
_____________________________________

Confidentiality Notice: This e-mail message, including any attachments, is
for the sole use of intended recipient(s) and may contain confidential and
privileged information. Any unauthorized review, use, disclosure or
distribution is prohibited unless instructed to do so by the original
author. If you are not the intended recipient, please contact the sender by
reply e-mail and destroy all copies of the original message.
