### ISSUE TITLE
opens new blank tab when sending page

### ISSUE THREAD

**Issue by pegasus227** [stadler/SendPage#21]
This seems to be a new side effect of this extension.  When I right click on "send this page" the email client opens and new email as well as opening a new tab (in chrome) it is a blank tab and I then have to close the tab.  I don't know why this is happening or how to stop it.  Other than this new quirk the extension works just as I expect it to work.

**Comment by stadler** [comment]
In the options page of the extension you can choose between Local or Web Mail Client.
Change the option to 'Local Mail Client' and your problem should be solved.
Let me know if the problem remains.

**Comment by pegasus227** [comment]
Thanks so much - I couldn't figure out what change - works perfectly!
