### ISSUE TITLE
shaky screen on option

### ISSUE THREAD

**Issue by dmatusow** [stadler/SendPage#22]
I like this extension, but I have noticed recently that when I go to set the options, the screen jumps all around.  I have to close all chrome pages and HOPE that this clears it up so I can set the option.  I'm going to look at the code, but this interface is new to me so I thought I'd send this over.

**Comment by stadler** [comment]
Hey @dmatusow 
Unfortunately I can't reproduce this... Could you make a screenshot/video or anything alike that shows the behaviour?
Do you use Web or Local Mail Client? Which E-Mail Client?
Did you have a Look at [the troubleshooting section](https://github.com/stadler/SendPage/blob/master/README.md#nothing-happens-when-i-click-send-page)
