### ISSUE TITLE
dont work with Brave browser

### ISSUE THREAD

**Issue by bimbachi** [stadler/SendPage#24]
don't work with Brave browser

**Comment by bimbachi** [comment]
It works.  but not under "local mail client" choice, when this was chosen my local mail didn't open. when switched to "web browser client" it opened my local email software.

**Comment by stadler** [comment]
It tested it today with Brave Version 1.69.153 Chromium: 128.0.6613.85 (Offizieller Build) (arm64) and it worked without problems.
The "web browser client" is more of a workaround to avoid problems with web mail clients. But also with that option it will only open your default browser as explained here: 
https://github.com/stadler/SendPage#nothing-happens-when-i-click-send-page
