### ISSUE TITLE
Wrong Characters from latin languages

### ISSUE THREAD

**Issue by lombas** [stadler/SendPage#8]
First of all, thank you for this app.
Trying to send a page in portuguese with accent, teh characters get all messed up, like in the picture.
![sem titulo](https://cloud.githubusercontent.com/assets/898124/8889545/c2515924-32b4-11e5-8686-7f207f37d469.jpg)

using windows 8 64bit, chrome 32bit  Version 43.0.2357.134 m

thanks

**Comment by stadler** [comment]
Hi lombas

First of all thanks for creating the issue.
The issue is fixed. Feel free to test it.

Cheers
